java_binary(
  name = "tlc2tlc",
  runtime_deps = ["@tla2tools//jar"],
  main_class = "tlc2.TLC",
  visibility = ["//visibility:public"],
)

py_binary(
  name = "tlc_runner",
  srcs = ["tlc_runner.py"],
  visibility = ["//visibility:public"],
)
